@TestOn('browser')
library test.generated_runner_test;

// Generated by `pub run dart_dev gen-test-runner -d test/ -e Environment.browser --genHtml`

import './action_provider_test.dart' as action_provider_test;
import './attachments_module_test.dart' as attachments_module_test;
import './attachments_store_test.dart' as attachments_store_test;
import './components/attachments_container_test.dart' as components_attachments_container_test;
import './components/attachments_panel_toolbar_test.dart' as components_attachments_panel_toolbar_test;
import './components/utils_test.dart' as components_utils_test;
import './models/group_test.dart' as models_group_test;
import './models/tree_node_test.dart' as models_tree_node_test;
import './thread_pool/thread_pool_test.dart' as thread_pool_thread_pool_test;
import './w_annotations_service/service_adapters/attachments_service_test.dart' as w_annotations_service_service_adapters_attachments_service_test;
import 'package:test/test.dart';
import 'package:dart_dev/checked_mode.dart';
import 'package:react/react_client.dart' as react_client;
import 'package:web_skin_dart/ui_core.dart';
import 'package:w_transport/mock.dart';

void main() {
  react_client.setClientConfiguration();
  enableTestMode();
  configureWTransportForTest();
  action_provider_test.main();
  attachments_module_test.main();
  attachments_store_test.main();
  components_attachments_container_test.main();
  components_attachments_panel_toolbar_test.main();
  components_utils_test.main();
  models_group_test.main();
  models_tree_node_test.main();
  thread_pool_thread_pool_test.main();
  w_annotations_service_service_adapters_attachments_service_test.main();
}