codecov:
  url: "https://codecov.workiva.net"
  branch: master

coverage:
  precision: 2
  round: down
  range: "40...75"
  ignore:
    - "docs"
    - "tool"
    - "lib/sass"
  status:
    project: yes
    patch: yes
    changes: no

comment:
  layout: header, diff, changes, sunburst, uncovered, tree
  behavior: default
  require_changes: no
